export enum CountryEnum {
  AFGHANISTAN = 'AF',
  ALAND_ISLANDS = 'AX',
  ALBANIA = 'AL',
  ALGERIA = 'DZ',
  AMERICAN_SAMOA = 'AS',
  ANDORRA = 'AD',
  ANGOLA = 'AO',
  ANGUILLA = 'AI',
  ANTARCTICA = 'AQ',
  ANTIGUA_AND_BARBUDA = 'AG',
  ARGENTINA = 'AR',
  ARMENIA = 'AM',
  ARUBA = 'AW',
  AUSTRALIA = 'AU',
  AUSTRIA = 'AT',
  AZERBAIJAN = 'AZ',
  BAHAMAS = 'BS',
  BAHRAIN = 'BH',
  BANGLADESH = 'BD',
  BARBADOS = 'BB',
  BELARUS = 'BY',
  BELGIUM = 'BE',
  BELIZE = 'BZ',
  BENIN = 'BJ',
  BERMUDA = 'BM',
  BHUTAN = 'BT',
  BOLIVIA_PLURINATIONAL_STATE_OF = 'BO',
  BONAIRE_SINT_EUSTATIUS_AND_SABA = 'BQ',
  BOSNIA_AND_HERZEGOVINA = 'BA',
  BOTSWANA = 'BW',
  BOUVET_ISLAND = 'BV',
  BRAZIL = 'BR',
  BRITISH_INDIAN_OCEAN_TERRITORY = 'IO',
  BRUNEI_DARUSSALAM = 'BN',
  BULGARIA = 'BG',
  BURKINA_FASO = 'BF',
  BURUNDI = 'BI',
  CAMBODIA = 'KH',
  CAMEROON = 'CM',
  CANADA = 'CA',
  CAPE_VERDE = 'CV',
  CAYMAN_ISLANDS = 'KY',
  CENTRAL_AFRICAN_REPUBLIC = 'CF',
  CHAD = 'TD',
  CHILE = 'CL',
  CHINA = 'CN',
  CHRISTMAS_ISLAND = 'CX',
  COCOS_KEELING_ISLANDS = 'CC',
  COLOMBIA = 'CO',
  COMOROS = 'KM',
  CONGO = 'CG',
  CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE = 'CD',
  COOK_ISLANDS = 'CK',
  COSTA_RICA = 'CR',
  CN_TE_D_IVOIR = 'CI',
  CROATIA = 'HR',
  CUBA = 'CU',
  CURACAO = 'CW',
  CYPRUS = 'CY',
  CZECH_REPUBLIC = 'CZ',
  DENMARK = 'DK',
  DJIBOUTI = 'DJ',
  DOMINICA = 'DM',
  DOMINICAN_REPUBLIC = 'DO',
  ECUADOR = 'EC',
  EGYPT = 'EG',
  EL_SALVADOR = 'SV',
  EQUATORIAL_GUINEA = 'GQ',
  ERITREA = 'ER',
  ESTONIA = 'EE',
  ETHIOPIA = 'ET',
  FALKLAND_ISLANDS_MALVINAS = 'FK',
  FARO_ISLANDS = 'FO',
  FIJI = 'FJ',
  FINLAND = 'FI',
  FRANCE = 'FR',
  FRENCH_GUIANA = 'GF',
  FRENCH_POLYNESIA = 'PF',
  FRENCH_SOUTHERN_TERRITORIES = 'TF',
  GABON = 'GA',
  GAMBIA = 'GM',
  GEORGIA = 'GE',
  GERMANY = 'DE',
  GHANA = 'GH',
  GIBRALTAR = 'GI',
  GREECE = 'GR',
  GREENLAND = 'GL',
  GRENADA = 'GD',
  GUADELOUPE = 'GP',
  GUAM = 'GU',
  GUATEMALA = 'GT',
  GUERNSEY = 'GG',
  GUINEA = 'GN',
  GUINEA_BISSAU = 'GW',
  GUYANA = 'GY',
  HAITI = 'HT',
  HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM',
  HOLY_SEE_VATICAN_CITY_STATE = 'VA',
  HONDURAS = 'HN',
  HONG_KONG = 'HK',
  HUNGARY = 'HU',
  ICELAND = 'IS',
  INDIA = 'IN',
  INDONESIA = 'ID',
  IRAN_ISLAMIC_REPUBLIC_OF = 'IR',
  IRAQ = 'IQ',
  IRELAND = 'IE',
  ISLE_OF_MAN = 'IM',
  ISRAEL = 'IL',
  ITALY = 'IT',
  JAMAICA = 'JM',
  JAPAN = 'JP',
  JERSEY = 'JE',
  JORDAN = 'JO',
  KAZAKHSTAN = 'KZ',
  KENYA = 'KE',
  KIRIBATI = 'KI',
  KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF = 'KP',
  KOREA_REPUBLIC_OF = 'KR',
  KUWAIT = 'KW',
  KYRGYZSTAN = 'KG',
  LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 'LA',
  LATVIA = 'LV',
  LEBANON = 'LB',
  LESOTHO = 'LS',
  LIBERIA = 'LR',
  LIBYA = 'LY',
  LIECHTENSTEIN = 'LI',
  LITHUANIA = 'LT',
  LUXEMBOURG = 'LU',
  MACAO = 'MO',
  SKOPJE = 'MK',
  MADAGASCAR = 'MG',
  MALAWI = 'MW',
  MALAYSIA = 'MY',
  MALDIVES = 'MV',
  MALI = 'ML',
  MALTA = 'MT',
  MARSHALL_ISLANDS = 'MH',
  MARTINIQUE = 'MQ',
  MAURITANIA = 'MR',
  MAURITIUS = 'MU',
  TUNISIA = 'TN',
  TURKEY = 'TR',
  TURKMENISTAN = 'TM',
  TURKS_AND_CAICOS_ISLANDS = 'TC',
  TUVALU = 'TV',
  UGANDA = 'UG',
  UKRAINE = 'UA',
  UNITED_ARAB_EMIRATES = 'AE',
  UNITED_KINGDOM = 'GB',
  UNITED_STATES = 'US',
  UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM',
  URUGUAY = 'UY',
  UZBEKISTAN = 'UZ',
  VANUATU = 'VU',
  VENEZUELA_BOLIVARIAN_REPUBLIC_OF = 'VE',
  VIET_NAM = 'VN',
  VIRGIN_ISLANDS_BRITISH = 'VG',
  VIRGIN_ISLANDS_US = 'VI',
  WALLIS_AND_FUTUNA = 'WF',
  WESTERN_SAHARA = 'EH',
  YEMEN = 'YE',
  ZAMBIA = 'ZM',
  ZIMBABWE = 'ZW',
  MAYOTTE = 'YT',
  MEXICO = 'MX',
  MICRONESIA_FEDERATED_STATES_OF = 'FM',
  MOLDOVA_REPUBLIC_OF = 'MD',
  MONACO = 'MC',
  MONGOLIA = 'MN',
  MONTENEGRO = 'ME',
  MONTSERRAT = 'MS',
  MOROCCO = 'MA',
  MOZAMBIQUE = 'MZ',
  MYANMAR = 'MM',
  NAMIBIA = 'NA',
  NAURU = 'NR',
  NEPAL = 'NP',
  NETHERLANDS = 'NL',
  NEW_CALEDONIA = 'NC',
  NEW_ZEALAND = 'NZ',
  NICARAGUA = 'NI',
  NIGER = 'NE',
  NIGERIA = 'NG',
  NIUE = 'NU',
  NORFOLK_ISLAND = 'NF',
  NORTHERN_MARIANA_ISLANDS = 'MP',
  NORWAY = 'NO',
  OMAN = 'OM',
  PAKISTAN = 'PK',
  PALAU = 'PW',
  PALESTINE_STATE_OF = 'PS',
  PANAMA = 'PA',
  PAPUA_NEW_GUINEA = 'PG',
  PARAGUAY = 'PY',
  PERU = 'PE',
  PHILIPPINES = 'PH',
  PITCAIRN = 'PN',
  POLAND = 'PL',
  PORTUGAL = 'PT',
  PUERTO_RICO = 'PR',
  QATAR = 'QA',
  RN_UNIO = 'RE',
  ROMANIA = 'RO',
  RUSSIAN_FEDERATION = 'RU',
  RWANDA = 'RW',
  SAINT_BARTHN_LEM = 'BL',
  SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'SH',
  SAINT_KITTS_AND_NEVIS = 'KN',
  SAINT_LUCIA = 'LC',
  SAINT_MARTIN = 'MF',
  SAINT_PIERRE_AND_MIQUELON = 'PM',
  SAINT_VINCENT_AND_THE_GRENADINES = 'VC',
  SAMOA = 'WS',
  SAN_MARINO = 'SM',
  SAO_TOME_AND_PRINCIPE = 'ST',
  SAUDI_ARABIA = 'SA',
  SENEGAL = 'SN',
  SERBIA = 'RS',
  SEYCHELLES = 'SC',
  SIERRA_LEONE = 'SL',
  SINGAPORE = 'SG',
  SINT_MAARTEN = 'SX',
  SLOVAKIA = 'SK',
  SLOVENIA = 'SI',
  SOLOMON_ISLANDS = 'SB',
  SOMALIA = 'SO',
  SOUTH_AFRICA = 'ZA',
  SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'GS',
  SOUTH_SUDAN = 'SS',
  SPAIN = 'ES',
  SRI_LANKA = 'LK',
  SUDAN = 'SD',
  SURINAME = 'SR',
  SVALBARD_AND_JAN_MAYEN = 'SJ',
  SWAZILAND = 'SZ',
  SWEDEN = 'SE',
  SWITZERLAND = 'CH',
  SYRIAN_ARAB_REPUBLIC = 'SY',
  TAIWAN_PROVINCE_OF_CHINA = 'TW',
  TAJIKISTAN = 'TJ',
  TANZANIA_UNITED_REPUBLIC_OF = 'TZ',
  THAILAND = 'TH',
  TIMOR_LESTE = 'TL',
  TOGO = 'TG',
  TOKELAU = 'TK',
  TONGA = 'TO',
  TRINIDAD_AND_TOBAGO = 'TT',
}

// TODO θέλουμε JSONSchema
export interface CountryDto {
  name: string;
  code: string;
  isEurope: boolean;
}

// Θέλουμε χώρες ευρώπης και ευρωζώνη 
export const EU_EEA_COUNTRIES = new Set<CountryEnum>([
  CountryEnum.AUSTRIA,
  CountryEnum.BELGIUM,
  CountryEnum.BULGARIA,
  CountryEnum.CROATIA,
  CountryEnum.CYPRUS,
  CountryEnum.CZECH_REPUBLIC,
  CountryEnum.DENMARK,
  CountryEnum.ESTONIA,
  CountryEnum.FINLAND,
  CountryEnum.FRANCE,
  CountryEnum.GERMANY,
  CountryEnum.GREECE,
  CountryEnum.HUNGARY,
  CountryEnum.ICELAND,
  CountryEnum.IRELAND,
  CountryEnum.ITALY,
  CountryEnum.LATVIA,
  CountryEnum.LIECHTENSTEIN,
  CountryEnum.LITHUANIA,
  CountryEnum.LUXEMBOURG,
  CountryEnum.MALTA,
  CountryEnum.NETHERLANDS,
  CountryEnum.NORWAY,
  CountryEnum.POLAND,
  CountryEnum.PORTUGAL,
  CountryEnum.ROMANIA,
  CountryEnum.SLOVAKIA,
  CountryEnum.SLOVENIA,
  CountryEnum.SPAIN,
  CountryEnum.SWEDEN,
]);

export const EUROZONE_COUNTRIES = new Set<CountryEnum>([
  CountryEnum.AUSTRIA,
  CountryEnum.BELGIUM,
  CountryEnum.CROATIA,
  CountryEnum.CYPRUS,
  CountryEnum.ESTONIA,
  CountryEnum.FINLAND,
  CountryEnum.FRANCE,
  CountryEnum.GERMANY,
  CountryEnum.GREECE,
  CountryEnum.IRELAND,
  CountryEnum.ITALY,
  CountryEnum.LATVIA,
  CountryEnum.LITHUANIA,
  CountryEnum.LUXEMBOURG,
  CountryEnum.MALTA,
  CountryEnum.NETHERLANDS,
  CountryEnum.PORTUGAL,
  CountryEnum.SLOVAKIA,
  CountryEnum.SLOVENIA,
  CountryEnum.SPAIN,
]);

export const BASE_COUNTRY_DATA: Record<CountryEnum, { name: string; code: CountryEnum; isEurope?: boolean }> = {
  [CountryEnum.AFGHANISTAN]: { name: 'Afghanistan', code: CountryEnum.AFGHANISTAN },
  [CountryEnum.ALAND_ISLANDS]: { name: 'Åland Islands', code: CountryEnum.ALAND_ISLANDS },
  [CountryEnum.ALBANIA]: { name: 'Albania', code: CountryEnum.ALBANIA },
  [CountryEnum.ALGERIA]: { name: 'Algeria', code: CountryEnum.ALGERIA },
  [CountryEnum.AMERICAN_SAMOA]: { name: 'American Samoa', code: CountryEnum.AMERICAN_SAMOA },
  [CountryEnum.ANDORRA]: { name: 'Andorra', code: CountryEnum.ANDORRA },
  [CountryEnum.ANGOLA]: { name: 'Angola', code: CountryEnum.ANGOLA },
  [CountryEnum.ANGUILLA]: { name: 'Anguilla', code: CountryEnum.ANGUILLA },
  [CountryEnum.ANTARCTICA]: { name: 'Antarctica', code: CountryEnum.ANTARCTICA },
  [CountryEnum.ANTIGUA_AND_BARBUDA]: {
    name: 'Antigua and Barbuda',
    code: CountryEnum.ANTIGUA_AND_BARBUDA,
  },
  [CountryEnum.ARGENTINA]: { name: 'Argentina', code: CountryEnum.ARGENTINA },
  [CountryEnum.ARMENIA]: { name: 'Armenia', code: CountryEnum.ARMENIA },
  [CountryEnum.ARUBA]: { name: 'Aruba', code: CountryEnum.ARUBA },
  [CountryEnum.AUSTRALIA]: { name: 'Australia', code: CountryEnum.AUSTRALIA },
  [CountryEnum.AUSTRIA]: {
    name: 'Austria',
    code: CountryEnum.AUSTRIA,
    isEurope: true,
  },
  [CountryEnum.AZERBAIJAN]: { name: 'Azerbaijan', code: CountryEnum.AZERBAIJAN },
  [CountryEnum.BAHAMAS]: { name: 'Bahamas', code: CountryEnum.BAHAMAS },
  [CountryEnum.BAHRAIN]: { name: 'Bahrain', code: CountryEnum.BAHRAIN },
  [CountryEnum.BANGLADESH]: { name: 'Bangladesh', code: CountryEnum.BANGLADESH },
  [CountryEnum.BARBADOS]: { name: 'Barbados', code: CountryEnum.BARBADOS },
  [CountryEnum.BELARUS]: { name: 'Belarus', code: CountryEnum.BELARUS },
  [CountryEnum.BELGIUM]: {
    name: 'Belgium',
    code: CountryEnum.BELGIUM,
    isEurope: true,
  },
  [CountryEnum.BELIZE]: { name: 'Belize', code: CountryEnum.BELIZE },
  [CountryEnum.BENIN]: { name: 'Benin', code: CountryEnum.BENIN },
  [CountryEnum.BERMUDA]: { name: 'Bermuda', code: CountryEnum.BERMUDA },
  [CountryEnum.BHUTAN]: { name: 'Bhutan', code: CountryEnum.BHUTAN },
  [CountryEnum.BOLIVIA_PLURINATIONAL_STATE_OF]: { name: 'Bolivia', code: CountryEnum.BOLIVIA_PLURINATIONAL_STATE_OF },
  [CountryEnum.BONAIRE_SINT_EUSTATIUS_AND_SABA]: {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: CountryEnum.BONAIRE_SINT_EUSTATIUS_AND_SABA,
  },
  [CountryEnum.BOSNIA_AND_HERZEGOVINA]: {
    name: 'Bosnia and Herzegovina',
    code: CountryEnum.BOSNIA_AND_HERZEGOVINA,
  },
  [CountryEnum.BOTSWANA]: { name: 'Botswana', code: CountryEnum.BOTSWANA },
  [CountryEnum.BOUVET_ISLAND]: { name: 'Bouvet Island', code: CountryEnum.BOUVET_ISLAND },
  [CountryEnum.BRAZIL]: { name: 'Brazil', code: CountryEnum.BRAZIL },
  [CountryEnum.BRITISH_INDIAN_OCEAN_TERRITORY]: {
    name: 'British Indian Ocean Territory',
    code: CountryEnum.BRITISH_INDIAN_OCEAN_TERRITORY,
  },
  [CountryEnum.BRUNEI_DARUSSALAM]: { name: 'Brunei', code: CountryEnum.BRUNEI_DARUSSALAM },
  [CountryEnum.BULGARIA]: {
    name: 'Bulgaria',
    code: CountryEnum.BULGARIA,
    isEurope: true,
  },
  [CountryEnum.BURKINA_FASO]: { name: 'Burkina Faso', code: CountryEnum.BURKINA_FASO },
  [CountryEnum.BURUNDI]: { name: 'Burundi', code: CountryEnum.BURUNDI },
  [CountryEnum.CAMBODIA]: { name: 'Cambodia', code: CountryEnum.CAMBODIA },
  [CountryEnum.CAMEROON]: { name: 'Cameroon', code: CountryEnum.CAMEROON },
  [CountryEnum.CANADA]: { name: 'Canada', code: CountryEnum.CANADA },
  [CountryEnum.CAPE_VERDE]: { name: 'Cape Verde', code: CountryEnum.CAPE_VERDE },
  [CountryEnum.CAYMAN_ISLANDS]: { name: 'Cayman Islands', code: CountryEnum.CAYMAN_ISLANDS },
  [CountryEnum.CENTRAL_AFRICAN_REPUBLIC]: {
    name: 'Central African Republic',
    code: CountryEnum.CENTRAL_AFRICAN_REPUBLIC,
  },
  [CountryEnum.CHAD]: { name: 'Chad', code: CountryEnum.CHAD },
  [CountryEnum.CHILE]: { name: 'Chile', code: CountryEnum.CHILE },
  [CountryEnum.CHINA]: { name: 'China', code: CountryEnum.CHINA },
  [CountryEnum.CHRISTMAS_ISLAND]: { name: 'Christmas Island', code: CountryEnum.CHRISTMAS_ISLAND },
  [CountryEnum.COCOS_KEELING_ISLANDS]: { name: 'Cocos (Keeling) Islands', code: CountryEnum.COCOS_KEELING_ISLANDS },
  [CountryEnum.COLOMBIA]: { name: 'Colombia', code: CountryEnum.COLOMBIA },
  [CountryEnum.COMOROS]: { name: 'Comoros', code: CountryEnum.COMOROS },
  [CountryEnum.CONGO]: { name: 'Congo', code: CountryEnum.CONGO },
  [CountryEnum.CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE]: {
    name: 'Congo, Democratic Republic of the',
    code: CountryEnum.CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE,
  },
  [CountryEnum.COOK_ISLANDS]: { name: 'Cook Islands', code: CountryEnum.COOK_ISLANDS },
  [CountryEnum.COSTA_RICA]: { name: 'Costa Rica', code: CountryEnum.COSTA_RICA },
  [CountryEnum.CN_TE_D_IVOIR]: { name: "Côte d'Ivoire", code: CountryEnum.CN_TE_D_IVOIR },
  [CountryEnum.CROATIA]: {
    name: 'Croatia',
    code: CountryEnum.CROATIA,
    isEurope: true,
  },
  [CountryEnum.CUBA]: { name: 'Cuba', code: CountryEnum.CUBA },
  [CountryEnum.CURACAO]: { name: 'Curaçao', code: CountryEnum.CURACAO },
  [CountryEnum.CYPRUS]: {
    name: 'Cyprus',
    code: CountryEnum.CYPRUS,
    isEurope: true,
  },
  [CountryEnum.CZECH_REPUBLIC]: {
    name: 'Czech Republic',
    code: CountryEnum.CZECH_REPUBLIC,
    isEurope: true,
  },
  [CountryEnum.DENMARK]: {
    name: 'Denmark',
    code: CountryEnum.DENMARK,
    isEurope: true,
  },
  [CountryEnum.DJIBOUTI]: { name: 'Djibouti', code: CountryEnum.DJIBOUTI },
  [CountryEnum.DOMINICA]: { name: 'Dominica', code: CountryEnum.DOMINICA },
  [CountryEnum.DOMINICAN_REPUBLIC]: { name: 'Dominican Republic', code: CountryEnum.DOMINICAN_REPUBLIC },
  [CountryEnum.ECUADOR]: { name: 'Ecuador', code: CountryEnum.ECUADOR },
  [CountryEnum.EGYPT]: { name: 'Egypt', code: CountryEnum.EGYPT },
  [CountryEnum.EL_SALVADOR]: { name: 'El Salvador', code: CountryEnum.EL_SALVADOR },
  [CountryEnum.EQUATORIAL_GUINEA]: { name: 'Equatorial Guinea', code: CountryEnum.EQUATORIAL_GUINEA },
  [CountryEnum.ERITREA]: { name: 'Eritrea', code: CountryEnum.ERITREA },
  [CountryEnum.ESTONIA]: {
    name: 'Estonia',
    code: CountryEnum.ESTONIA,
    isEurope: true,
  },
  [CountryEnum.ETHIOPIA]: { name: 'Ethiopia', code: CountryEnum.ETHIOPIA },
  [CountryEnum.FALKLAND_ISLANDS_MALVINAS]: {
    name: 'Falkland Islands (Malvinas)',
    code: CountryEnum.FALKLAND_ISLANDS_MALVINAS,
  },
  [CountryEnum.FARO_ISLANDS]: { name: 'Faroe Islands', code: CountryEnum.FARO_ISLANDS },
  [CountryEnum.FIJI]: { name: 'Fiji', code: CountryEnum.FIJI },
  [CountryEnum.FINLAND]: {
    name: 'Finland',
    code: CountryEnum.FINLAND,
    isEurope: true,
  },
  [CountryEnum.FRANCE]: {
    name: 'France',
    code: CountryEnum.FRANCE,
    isEurope: true,
  },
  [CountryEnum.FRENCH_GUIANA]: { name: 'French Guiana', code: CountryEnum.FRENCH_GUIANA },
  [CountryEnum.FRENCH_POLYNESIA]: { name: 'French Polynesia', code: CountryEnum.FRENCH_POLYNESIA },
  [CountryEnum.FRENCH_SOUTHERN_TERRITORIES]: {
    name: 'French Southern Territories',
    code: CountryEnum.FRENCH_SOUTHERN_TERRITORIES,
  },
  [CountryEnum.GABON]: { name: 'Gabon', code: CountryEnum.GABON },
  [CountryEnum.GAMBIA]: { name: 'Gambia', code: CountryEnum.GAMBIA },
  [CountryEnum.GEORGIA]: { name: 'Georgia', code: CountryEnum.GEORGIA },
  [CountryEnum.GERMANY]: {
    name: 'Germany',
    code: CountryEnum.GERMANY,
    isEurope: true,
  },
  [CountryEnum.GHANA]: { name: 'Ghana', code: CountryEnum.GHANA },
  [CountryEnum.GIBRALTAR]: { name: 'Gibraltar', code: CountryEnum.GIBRALTAR },
  [CountryEnum.GREECE]: {
    name: 'Greece',
    code: CountryEnum.GREECE,
    isEurope: true,
  },
  [CountryEnum.GREENLAND]: { name: 'Greenland', code: CountryEnum.GREENLAND },
  [CountryEnum.GRENADA]: { name: 'Grenada', code: CountryEnum.GRENADA },
  [CountryEnum.GUADELOUPE]: { name: 'Guadeloupe', code: CountryEnum.GUADELOUPE },
  [CountryEnum.GUAM]: { name: 'Guam', code: CountryEnum.GUAM },
  [CountryEnum.GUATEMALA]: { name: 'Guatemala', code: CountryEnum.GUATEMALA },
  [CountryEnum.GUERNSEY]: { name: 'Guernsey', code: CountryEnum.GUERNSEY },
  [CountryEnum.GUINEA]: { name: 'Guinea', code: CountryEnum.GUINEA },
  [CountryEnum.GUINEA_BISSAU]: { name: 'Guinea-Bissau', code: CountryEnum.GUINEA_BISSAU },
  [CountryEnum.GUYANA]: { name: 'Guyana', code: CountryEnum.GUYANA },
  [CountryEnum.HAITI]: { name: 'Haiti', code: CountryEnum.HAITI },
  [CountryEnum.HEARD_ISLAND_AND_MCDONALD_ISLANDS]: {
    name: 'Heard Island and McDonald Islands',
    code: CountryEnum.HEARD_ISLAND_AND_MCDONALD_ISLANDS,
  },
  [CountryEnum.HOLY_SEE_VATICAN_CITY_STATE]: {
    name: 'Holy See (Vatican City State)',
    code: CountryEnum.HOLY_SEE_VATICAN_CITY_STATE,
  },
  [CountryEnum.HONDURAS]: { name: 'Honduras', code: CountryEnum.HONDURAS },
  [CountryEnum.HONG_KONG]: { name: 'Hong Kong', code: CountryEnum.HONG_KONG },
  [CountryEnum.HUNGARY]: {
    name: 'Hungary',
    code: CountryEnum.HUNGARY,
    isEurope: true,
  },
  [CountryEnum.ICELAND]: {
    name: 'Iceland',
    code: CountryEnum.ICELAND,
    isEurope: true,
  },
  [CountryEnum.INDIA]: { name: 'India', code: CountryEnum.INDIA },
  [CountryEnum.INDONESIA]: { name: 'Indonesia', code: CountryEnum.INDONESIA },
  [CountryEnum.IRAN_ISLAMIC_REPUBLIC_OF]: { name: 'Iran', code: CountryEnum.IRAN_ISLAMIC_REPUBLIC_OF },
  [CountryEnum.IRAQ]: { name: 'Iraq', code: CountryEnum.IRAQ },
  [CountryEnum.IRELAND]: {
    name: 'Ireland',
    code: CountryEnum.IRELAND,
    isEurope: true,
  },
  [CountryEnum.ISLE_OF_MAN]: { name: 'Isle of Man', code: CountryEnum.ISLE_OF_MAN },
  [CountryEnum.ISRAEL]: { name: 'Israel', code: CountryEnum.ISRAEL },
  [CountryEnum.ITALY]: {
    name: 'Italy',
    code: CountryEnum.ITALY,
    isEurope: true,
  },
  [CountryEnum.JAMAICA]: { name: 'Jamaica', code: CountryEnum.JAMAICA },
  [CountryEnum.JAPAN]: { name: 'Japan', code: CountryEnum.JAPAN },
  [CountryEnum.JERSEY]: { name: 'Jersey', code: CountryEnum.JERSEY },
  [CountryEnum.JORDAN]: { name: 'Jordan', code: CountryEnum.JORDAN },
  [CountryEnum.KAZAKHSTAN]: { name: 'Kazakhstan', code: CountryEnum.KAZAKHSTAN },
  [CountryEnum.KENYA]: { name: 'Kenya', code: CountryEnum.KENYA },
  [CountryEnum.KIRIBATI]: { name: 'Kiribati', code: CountryEnum.KIRIBATI },
  [CountryEnum.KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF]: {
    name: 'North Korea',
    code: CountryEnum.KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF,
  },
  [CountryEnum.KOREA_REPUBLIC_OF]: { name: 'South Korea', code: CountryEnum.KOREA_REPUBLIC_OF },
  [CountryEnum.KUWAIT]: { name: 'Kuwait', code: CountryEnum.KUWAIT },
  [CountryEnum.KYRGYZSTAN]: { name: 'Kyrgyzstan', code: CountryEnum.KYRGYZSTAN },
  [CountryEnum.LAO_PEOPLES_DEMOCRATIC_REPUBLIC]: { name: 'Laos', code: CountryEnum.LAO_PEOPLES_DEMOCRATIC_REPUBLIC },
  [CountryEnum.LATVIA]: {
    name: 'Latvia',
    code: CountryEnum.LATVIA,
    isEurope: true,
  },
  [CountryEnum.LEBANON]: { name: 'Lebanon', code: CountryEnum.LEBANON },
  [CountryEnum.LESOTHO]: { name: 'Lesotho', code: CountryEnum.LESOTHO },
  [CountryEnum.LIBERIA]: { name: 'Liberia', code: CountryEnum.LIBERIA },
  [CountryEnum.LIBYA]: { name: 'Libya', code: CountryEnum.LIBYA },
  [CountryEnum.LIECHTENSTEIN]: {
    name: 'Liechtenstein',
    code: CountryEnum.LIECHTENSTEIN,
    isEurope: true,
  },
  [CountryEnum.LITHUANIA]: {
    name: 'Lithuania',
    code: CountryEnum.LITHUANIA,
    isEurope: true,
  },
  [CountryEnum.LUXEMBOURG]: {
    name: 'Luxembourg',
    code: CountryEnum.LUXEMBOURG,
    isEurope: true,
  },
  [CountryEnum.MACAO]: { name: 'Macao', code: CountryEnum.MACAO },
  [CountryEnum.SKOPJE]: { name: 'North Macedonia', code: CountryEnum.SKOPJE },
  [CountryEnum.MADAGASCAR]: { name: 'Madagascar', code: CountryEnum.MADAGASCAR },
  [CountryEnum.MALAWI]: { name: 'Malawi', code: CountryEnum.MALAWI },
  [CountryEnum.MALAYSIA]: { name: 'Malaysia', code: CountryEnum.MALAYSIA },
  [CountryEnum.MALDIVES]: { name: 'Maldives', code: CountryEnum.MALDIVES },
  [CountryEnum.MALI]: { name: 'Mali', code: CountryEnum.MALI },
  [CountryEnum.MALTA]: {
    name: 'Malta',
    code: CountryEnum.MALTA,
    isEurope: true,
  },
  [CountryEnum.MARSHALL_ISLANDS]: { name: 'Marshall Islands', code: CountryEnum.MARSHALL_ISLANDS },
  [CountryEnum.MARTINIQUE]: { name: 'Martinique', code: CountryEnum.MARTINIQUE },
  [CountryEnum.MAURITANIA]: { name: 'Mauritania', code: CountryEnum.MAURITANIA },
  [CountryEnum.MAURITIUS]: { name: 'Mauritius', code: CountryEnum.MAURITIUS },
  [CountryEnum.TUNISIA]: { name: 'Tunisia', code: CountryEnum.TUNISIA },
  [CountryEnum.TURKEY]: { name: 'Turkey', code: CountryEnum.TURKEY },
  [CountryEnum.TURKMENISTAN]: { name: 'Turkmenistan', code: CountryEnum.TURKMENISTAN },
  [CountryEnum.TURKS_AND_CAICOS_ISLANDS]: {
    name: 'Turks and Caicos Islands',
    code: CountryEnum.TURKS_AND_CAICOS_ISLANDS,
  },
  [CountryEnum.TUVALU]: { name: 'Tuvalu', code: CountryEnum.TUVALU },
  [CountryEnum.UGANDA]: { name: 'Uganda', code: CountryEnum.UGANDA },
  [CountryEnum.UKRAINE]: { name: 'Ukraine', code: CountryEnum.UKRAINE },
  [CountryEnum.UNITED_ARAB_EMIRATES]: { name: 'United Arab Emirates', code: CountryEnum.UNITED_ARAB_EMIRATES },
  [CountryEnum.UNITED_KINGDOM]: { name: 'United Kingdom', code: CountryEnum.UNITED_KINGDOM },
  [CountryEnum.UNITED_STATES]: { name: 'United States', code: CountryEnum.UNITED_STATES },
  [CountryEnum.UNITED_STATES_MINOR_OUTLYING_ISLANDS]: {
    name: 'United States Minor Outlying Islands',
    code: CountryEnum.UNITED_STATES_MINOR_OUTLYING_ISLANDS,
  },
  [CountryEnum.URUGUAY]: { name: 'Uruguay', code: CountryEnum.URUGUAY },
  [CountryEnum.UZBEKISTAN]: { name: 'Uzbekistan', code: CountryEnum.UZBEKISTAN },
  [CountryEnum.VANUATU]: { name: 'Vanuatu', code: CountryEnum.VANUATU },
  [CountryEnum.VENEZUELA_BOLIVARIAN_REPUBLIC_OF]: { name: 'Venezuela', code: CountryEnum.VENEZUELA_BOLIVARIAN_REPUBLIC_OF },
  [CountryEnum.VIET_NAM]: { name: 'Vietnam', code: CountryEnum.VIET_NAM },
  [CountryEnum.VIRGIN_ISLANDS_BRITISH]: {
    name: 'Virgin Islands (British)',
    code: CountryEnum.VIRGIN_ISLANDS_BRITISH,
  },
  [CountryEnum.VIRGIN_ISLANDS_US]: { name: 'Virgin Islands (U.S.)', code: CountryEnum.VIRGIN_ISLANDS_US },
  [CountryEnum.WALLIS_AND_FUTUNA]: { name: 'Wallis and Futuna', code: CountryEnum.WALLIS_AND_FUTUNA },
  [CountryEnum.WESTERN_SAHARA]: { name: 'Western Sahara', code: CountryEnum.WESTERN_SAHARA },
  [CountryEnum.YEMEN]: { name: 'Yemen', code: CountryEnum.YEMEN },
  [CountryEnum.ZAMBIA]: { name: 'Zambia', code: CountryEnum.ZAMBIA },
  [CountryEnum.ZIMBABWE]: { name: 'Zimbabwe', code: CountryEnum.ZIMBABWE },
  [CountryEnum.MAYOTTE]: { name: 'Mayotte', code: CountryEnum.MAYOTTE },
  [CountryEnum.MEXICO]: { name: 'Mexico', code: CountryEnum.MEXICO },
  [CountryEnum.MICRONESIA_FEDERATED_STATES_OF]: { name: 'Micronesia', code: CountryEnum.MICRONESIA_FEDERATED_STATES_OF },
  [CountryEnum.MOLDOVA_REPUBLIC_OF]: { name: 'Moldova', code: CountryEnum.MOLDOVA_REPUBLIC_OF },
  [CountryEnum.MONACO]: { name: 'Monaco', code: CountryEnum.MONACO },
  [CountryEnum.MONGOLIA]: { name: 'Mongolia', code: CountryEnum.MONGOLIA },
  [CountryEnum.MONTENEGRO]: { name: 'Montenegro', code: CountryEnum.MONTENEGRO },
  [CountryEnum.MONTSERRAT]: { name: 'Montserrat', code: CountryEnum.MONTSERRAT },
  [CountryEnum.MOROCCO]: { name: 'Morocco', code: CountryEnum.MOROCCO },
  [CountryEnum.MOZAMBIQUE]: { name: 'Mozambique', code: CountryEnum.MOZAMBIQUE },
  [CountryEnum.MYANMAR]: { name: 'Myanmar', code: CountryEnum.MYANMAR },
  [CountryEnum.NAMIBIA]: { name: 'Namibia', code: CountryEnum.NAMIBIA },
  [CountryEnum.NAURU]: { name: 'Nauru', code: CountryEnum.NAURU },
  [CountryEnum.NEPAL]: { name: 'Nepal', code: CountryEnum.NEPAL },
  [CountryEnum.NETHERLANDS]: {
    name: 'Netherlands',
    code: CountryEnum.NETHERLANDS,
    isEurope: true,
  },
  [CountryEnum.NEW_CALEDONIA]: { name: 'New Caledonia', code: CountryEnum.NEW_CALEDONIA },
  [CountryEnum.NEW_ZEALAND]: { name: 'New Zealand', code: CountryEnum.NEW_ZEALAND },
  [CountryEnum.NICARAGUA]: { name: 'Nicaragua', code: CountryEnum.NICARAGUA },
  [CountryEnum.NIGER]: { name: 'Niger', code: CountryEnum.NIGER },
  [CountryEnum.NIGERIA]: { name: 'Nigeria', code: CountryEnum.NIGERIA },
  [CountryEnum.NIUE]: { name: 'Niue', code: CountryEnum.NIUE },
  [CountryEnum.NORFOLK_ISLAND]: { name: 'Norfolk Island', code: CountryEnum.NORFOLK_ISLAND },
  [CountryEnum.NORTHERN_MARIANA_ISLANDS]: {
    name: 'Northern Mariana Islands',
    code: CountryEnum.NORTHERN_MARIANA_ISLANDS,
  },
  [CountryEnum.NORWAY]: {
    name: 'Norway',
    code: CountryEnum.NORWAY,
    isEurope: true,
  },
  [CountryEnum.OMAN]: { name: 'Oman', code: CountryEnum.OMAN },
  [CountryEnum.PAKISTAN]: { name: 'Pakistan', code: CountryEnum.PAKISTAN },
  [CountryEnum.PALAU]: { name: 'Palau', code: CountryEnum.PALAU },
  [CountryEnum.PALESTINE_STATE_OF]: { name: 'Palestine', code: CountryEnum.PALESTINE_STATE_OF },
  [CountryEnum.PANAMA]: { name: 'Panama', code: CountryEnum.PANAMA },
  [CountryEnum.PAPUA_NEW_GUINEA]: { name: 'Papua New Guinea', code: CountryEnum.PAPUA_NEW_GUINEA },
  [CountryEnum.PARAGUAY]: { name: 'Paraguay', code: CountryEnum.PARAGUAY },
  [CountryEnum.PERU]: { name: 'Peru', code: CountryEnum.PERU },
  [CountryEnum.PHILIPPINES]: { name: 'Philippines', code: CountryEnum.PHILIPPINES },
  [CountryEnum.PITCAIRN]: { name: 'Pitcairn', code: CountryEnum.PITCAIRN },
  [CountryEnum.POLAND]: {
    name: 'Poland',
    code: CountryEnum.POLAND,
    isEurope: true,
  },
  [CountryEnum.PORTUGAL]: {
    name: 'Portugal',
    code: CountryEnum.PORTUGAL,
    isEurope: true,
  },
  [CountryEnum.PUERTO_RICO]: { name: 'Puerto Rico', code: CountryEnum.PUERTO_RICO },
  [CountryEnum.QATAR]: { name: 'Qatar', code: CountryEnum.QATAR },
  [CountryEnum.RN_UNIO]: { name: 'Réunion', code: CountryEnum.RN_UNIO },
  [CountryEnum.ROMANIA]: {
    name: 'Romania',
    code: CountryEnum.ROMANIA,
    isEurope: true,
  },
  [CountryEnum.RUSSIAN_FEDERATION]: { name: 'Russia', code: CountryEnum.RUSSIAN_FEDERATION },
  [CountryEnum.RWANDA]: { name: 'Rwanda', code: CountryEnum.RWANDA },
  [CountryEnum.SAINT_BARTHN_LEM]: { name: 'Saint Barthélemy', code: CountryEnum.SAINT_BARTHN_LEM },
  [CountryEnum.SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA]: {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    code: CountryEnum.SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA,
  },
  [CountryEnum.SAINT_KITTS_AND_NEVIS]: { name: 'Saint Kitts and Nevis', code: CountryEnum.SAINT_KITTS_AND_NEVIS },
  [CountryEnum.SAINT_LUCIA]: { name: 'Saint Lucia', code: CountryEnum.SAINT_LUCIA },
  [CountryEnum.SAINT_MARTIN]: { name: 'Saint Martin (French part)', code: CountryEnum.SAINT_MARTIN },
  [CountryEnum.SAINT_PIERRE_AND_MIQUELON]: {
    name: 'Saint Pierre and Miquelon',
    code: CountryEnum.SAINT_PIERRE_AND_MIQUELON,
  },
  [CountryEnum.SAINT_VINCENT_AND_THE_GRENADINES]: {
    name: 'Saint Vincent and the Grenadines',
    code: CountryEnum.SAINT_VINCENT_AND_THE_GRENADINES,
  },
  [CountryEnum.SAMOA]: { name: 'Samoa', code: CountryEnum.SAMOA },
  [CountryEnum.SAN_MARINO]: { name: 'San Marino', code: CountryEnum.SAN_MARINO },
  [CountryEnum.SAO_TOME_AND_PRINCIPE]: { name: 'Sao Tome and Principe', code: CountryEnum.SAO_TOME_AND_PRINCIPE },
  [CountryEnum.SAUDI_ARABIA]: { name: 'Saudi Arabia', code: CountryEnum.SAUDI_ARABIA },
  [CountryEnum.SENEGAL]: { name: 'Senegal', code: CountryEnum.SENEGAL },
  [CountryEnum.SERBIA]: { name: 'Serbia', code: CountryEnum.SERBIA },
  [CountryEnum.SEYCHELLES]: { name: 'Seychelles', code: CountryEnum.SEYCHELLES },
  [CountryEnum.SIERRA_LEONE]: { name: 'Sierra Leone', code: CountryEnum.SIERRA_LEONE },
  [CountryEnum.SINGAPORE]: { name: 'Singapore', code: CountryEnum.SINGAPORE },
  [CountryEnum.SINT_MAARTEN]: { name: 'Sint Maarten (Dutch part)', code: CountryEnum.SINT_MAARTEN },
  [CountryEnum.SLOVAKIA]: {
    name: 'Slovakia',
    code: CountryEnum.SLOVAKIA,
    isEurope: true,
  },
  [CountryEnum.SLOVENIA]: {
    name: 'Slovenia',
    code: CountryEnum.SLOVENIA,
    isEurope: true,
  },
  [CountryEnum.SOLOMON_ISLANDS]: { name: 'Solomon Islands', code: CountryEnum.SOLOMON_ISLANDS },
  [CountryEnum.SOMALIA]: { name: 'Somalia', code: CountryEnum.SOMALIA },
  [CountryEnum.SOUTH_AFRICA]: { name: 'South Africa', code: CountryEnum.SOUTH_AFRICA },
  [CountryEnum.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS]: {
    name: 'South Georgia and the South Sandwich Islands',
    code: CountryEnum.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
  },
  [CountryEnum.SOUTH_SUDAN]: { name: 'South Sudan', code: CountryEnum.SOUTH_SUDAN },
  [CountryEnum.SPAIN]: {
    name: 'Spain',
    code: CountryEnum.SPAIN,
    isEurope: true,
  },
  [CountryEnum.SRI_LANKA]: { name: 'Sri Lanka', code: CountryEnum.SRI_LANKA },
  [CountryEnum.SUDAN]: { name: 'Sudan', code: CountryEnum.SUDAN },
  [CountryEnum.SURINAME]: { name: 'Suriname', code: CountryEnum.SURINAME },
  [CountryEnum.SVALBARD_AND_JAN_MAYEN]: { name: 'Svalbard and Jan Mayen', code: CountryEnum.SVALBARD_AND_JAN_MAYEN },
  [CountryEnum.SWAZILAND]: { name: 'Eswatini', code: CountryEnum.SWAZILAND },
  [CountryEnum.SWEDEN]: {
    name: 'Sweden',
    code: CountryEnum.SWEDEN,
    isEurope: true,
  },
  [CountryEnum.SWITZERLAND]: { name: 'Switzerland', code: CountryEnum.SWITZERLAND },
  [CountryEnum.SYRIAN_ARAB_REPUBLIC]: { name: 'Syria', code: CountryEnum.SYRIAN_ARAB_REPUBLIC },
  [CountryEnum.TAIWAN_PROVINCE_OF_CHINA]: { name: 'Taiwan', code: CountryEnum.TAIWAN_PROVINCE_OF_CHINA },
  [CountryEnum.TAJIKISTAN]: { name: 'Tajikistan', code: CountryEnum.TAJIKISTAN },
  [CountryEnum.TANZANIA_UNITED_REPUBLIC_OF]: { name: 'Tanzania', code: CountryEnum.TANZANIA_UNITED_REPUBLIC_OF },
  [CountryEnum.THAILAND]: { name: 'Thailand', code: CountryEnum.THAILAND },
  [CountryEnum.TIMOR_LESTE]: { name: 'Timor-Leste', code: CountryEnum.TIMOR_LESTE },
  [CountryEnum.TOGO]: { name: 'Togo', code: CountryEnum.TOGO },
  [CountryEnum.TOKELAU]: { name: 'Tokelau', code: CountryEnum.TOKELAU },
  [CountryEnum.TONGA]: { name: 'Tonga', code: CountryEnum.TONGA },
  [CountryEnum.TRINIDAD_AND_TOBAGO]: { name: 'Trinidad and Tobago', code: CountryEnum.TRINIDAD_AND_TOBAGO },
};

export const COUNTRY_DATA: Record<CountryEnum, CountryDto> = Object.values(CountryEnum).reduce(
  (acc, code) => {
    const countryCode = code as CountryEnum;
    const base = BASE_COUNTRY_DATA[countryCode];
    acc[countryCode] = {
      ...base,
      isEurope: EU_EEA_COUNTRIES.has(countryCode) || false,
    };
    return acc;
  },
  {} as Record<CountryEnum, CountryDto>,
);
