export enum CurrencyEnum {
  EUR = 'EUR',
  USD = 'USD',
  GBP = 'GBP',
  CHF = 'CHF',
  SEK = 'SEK',
  NOK = 'NOK',
  DKK = 'DKK',
  PLN = 'PLN',
  CZK = 'CZK',
  HUF = 'HUF',
  RON = 'RON',
  BGN = 'BGN',
  TRY = 'TRY',
  RUB = 'RUB',
  JPY = 'JPY',
  CNY = 'CNY',
  AUD = 'AUD',
  NZD = 'NZD',
  CAD = 'CAD',
  ZAR = 'ZAR',
  INR = 'INR',
  MXN = 'MXN',
  BRL = 'BRL',
  ARS = 'ARS',
  CLP = 'CLP',
  COP = 'COP',
  PEN = 'PEN',
  UYU = 'UYU',
  VES = 'VES',
  ILS = 'ILS',
  AED = 'AED',
  SAR = 'SAR',
  KRW = 'KRW',
  SGD = 'SGD',
  HKD = 'HKD',
  TWD = 'TWD',
  THB = 'THB',
  MYR = 'MYR',
  IDR = 'IDR',
  PHP = 'PHP',
  VND = 'VND',
  // ISO 4217 currencies added to cover Core API's persisted CurrencyCodeEnum (issue #22)
  AFN = 'AFN',
  ALL = 'ALL',
  AMD = 'AMD',
  AOA = 'AOA',
  AWG = 'AWG',
  AZN = 'AZN',
  BAM = 'BAM',
  BBD = 'BBD',
  BDT = 'BDT',
  BHD = 'BHD',
  BIF = 'BIF',
  BMD = 'BMD',
  BND = 'BND',
  BOB = 'BOB',
  BSD = 'BSD',
  BTN = 'BTN',
  BWP = 'BWP',
  BYN = 'BYN',
  BZD = 'BZD',
  CDF = 'CDF',
  CRC = 'CRC',
  CUP = 'CUP',
  CVE = 'CVE',
  DJF = 'DJF',
  DOP = 'DOP',
  DZD = 'DZD',
  EGP = 'EGP',
  ERN = 'ERN',
  ETB = 'ETB',
  FJD = 'FJD',
  GEL = 'GEL',
  GHS = 'GHS',
  GMD = 'GMD',
  GNF = 'GNF',
  GTQ = 'GTQ',
  GYD = 'GYD',
  HNL = 'HNL',
  HTG = 'HTG',
  IQD = 'IQD',
  IRR = 'IRR',
  ISK = 'ISK',
  JMD = 'JMD',
  JOD = 'JOD',
  KES = 'KES',
  KGS = 'KGS',
  KHR = 'KHR',
  KMF = 'KMF',
  KWD = 'KWD',
  KYD = 'KYD',
  KZT = 'KZT',
  LAK = 'LAK',
  LBP = 'LBP',
  LKR = 'LKR',
  LRD = 'LRD',
  LSL = 'LSL',
  LYD = 'LYD',
  MAD = 'MAD',
  MDL = 'MDL',
  MGA = 'MGA',
  MKD = 'MKD',
  MMK = 'MMK',
  MNT = 'MNT',
  MOP = 'MOP',
  MUR = 'MUR',
  MVR = 'MVR',
  MWK = 'MWK',
  MZN = 'MZN',
  NAD = 'NAD',
  NGN = 'NGN',
  NIO = 'NIO',
  NPR = 'NPR',
  OMR = 'OMR',
  PAB = 'PAB',
  PGK = 'PGK',
  PKR = 'PKR',
  PYG = 'PYG',
  QAR = 'QAR',
  RSD = 'RSD',
  RWF = 'RWF',
  SBD = 'SBD',
  SDG = 'SDG',
  SLE = 'SLE',
  SOS = 'SOS',
  SRD = 'SRD',
  SSP = 'SSP',
  STN = 'STN',
  SYP = 'SYP',
  SZL = 'SZL',
  TJS = 'TJS',
  TMT = 'TMT',
  TND = 'TND',
  TOP = 'TOP',
  TTD = 'TTD',
  TZS = 'TZS',
  UAH = 'UAH',
  UGX = 'UGX',
  UZS = 'UZS',
  VED = 'VED',
  VUV = 'VUV',
  WST = 'WST',
  XAF = 'XAF',
  XCD = 'XCD',
  XCG = 'XCG',
  XOF = 'XOF',
  XPF = 'XPF',
  YER = 'YER',
  ZMW = 'ZMW',
  ZWG = 'ZWG',
}

/**
 * Display metadata for a single currency code.
 *
 * @description - The `code` mirrors the key of {@link CURRENCY_CATALOG}, so a single entry
 *                stays self-describing once it is detached from the map (e.g. serialized
 *                to a client as a list).
 */
export interface CurrencyMetadata {
  /** English currency name (ISO 4217 / CLDR wording). */
  name: string;
  /** Commonly used currency symbol. Falls back to the three-letter code when no distinct symbol exists. */
  symbol: string;
  /** ISO 4217 currency code. */
  code: CurrencyEnum;
}

const BASE_CURRENCY_DATA: Record<
  CurrencyEnum,
  Omit<CurrencyMetadata, 'code'>
> = {
  [CurrencyEnum.EUR]: { name: 'Euro', symbol: '€' },
  [CurrencyEnum.USD]: { name: 'U.S. Dollar', symbol: '$' },
  [CurrencyEnum.GBP]: { name: 'British Pound', symbol: '£' },
  [CurrencyEnum.CHF]: { name: 'Swiss Franc', symbol: 'CHF' },
  [CurrencyEnum.SEK]: { name: 'Swedish Krona', symbol: 'kr' },
  [CurrencyEnum.NOK]: { name: 'Norwegian Krone', symbol: 'kr' },
  [CurrencyEnum.DKK]: { name: 'Danish Krone', symbol: 'kr' },
  [CurrencyEnum.PLN]: { name: 'Polish Złoty', symbol: 'zł' },
  [CurrencyEnum.CZK]: { name: 'Czech Koruna', symbol: 'Kč' },
  [CurrencyEnum.HUF]: { name: 'Hungarian Forint', symbol: 'Ft' },
  [CurrencyEnum.RON]: { name: 'Romanian Leu', symbol: 'lei' },
  [CurrencyEnum.BGN]: { name: 'Bulgarian Lev', symbol: 'лв' },
  [CurrencyEnum.TRY]: { name: 'Turkish Lira', symbol: '₺' },
  [CurrencyEnum.RUB]: { name: 'Russian Ruble', symbol: '₽' },
  [CurrencyEnum.JPY]: { name: 'Japanese Yen', symbol: '¥' },
  [CurrencyEnum.CNY]: { name: 'Chinese Yuan', symbol: '¥' },
  [CurrencyEnum.AUD]: { name: 'Australian Dollar', symbol: 'A$' },
  [CurrencyEnum.NZD]: { name: 'New Zealand Dollar', symbol: 'NZ$' },
  [CurrencyEnum.CAD]: { name: 'Canadian Dollar', symbol: 'CA$' },
  [CurrencyEnum.ZAR]: { name: 'South African Rand', symbol: 'R' },
  [CurrencyEnum.INR]: { name: 'Indian Rupee', symbol: '₹' },
  [CurrencyEnum.MXN]: { name: 'Mexican Peso', symbol: 'MX$' },
  [CurrencyEnum.BRL]: { name: 'Brazilian Real', symbol: 'R$' },
  [CurrencyEnum.ARS]: { name: 'Argentine Peso', symbol: '$' },
  [CurrencyEnum.CLP]: { name: 'Chilean Peso', symbol: '$' },
  [CurrencyEnum.COP]: { name: 'Colombian Peso', symbol: '$' },
  [CurrencyEnum.PEN]: { name: 'Peruvian Sol', symbol: 'S/' },
  [CurrencyEnum.UYU]: { name: 'Uruguayan Peso', symbol: '$U' },
  [CurrencyEnum.VES]: { name: 'Venezuelan Bolívar', symbol: 'Bs.' },
  [CurrencyEnum.ILS]: { name: 'Israeli New Shekel', symbol: '₪' },
  [CurrencyEnum.AED]: { name: 'United Arab Emirates Dirham', symbol: 'د.إ' },
  [CurrencyEnum.SAR]: { name: 'Saudi Riyal', symbol: 'ر.س' },
  [CurrencyEnum.KRW]: { name: 'South Korean Won', symbol: '₩' },
  [CurrencyEnum.SGD]: { name: 'Singapore Dollar', symbol: 'S$' },
  [CurrencyEnum.HKD]: { name: 'Hong Kong Dollar', symbol: 'HK$' },
  [CurrencyEnum.TWD]: { name: 'New Taiwan Dollar', symbol: 'NT$' },
  [CurrencyEnum.THB]: { name: 'Thai Baht', symbol: '฿' },
  [CurrencyEnum.MYR]: { name: 'Malaysian Ringgit', symbol: 'RM' },
  [CurrencyEnum.IDR]: { name: 'Indonesian Rupiah', symbol: 'Rp' },
  [CurrencyEnum.PHP]: { name: 'Philippine Peso', symbol: '₱' },
  [CurrencyEnum.VND]: { name: 'Vietnamese Dong', symbol: '₫' },
  [CurrencyEnum.AFN]: { name: 'Afghan Afghani', symbol: '؋' },
  [CurrencyEnum.ALL]: { name: 'Albanian Lek', symbol: 'L' },
  [CurrencyEnum.AMD]: { name: 'Armenian Dram', symbol: '֏' },
  [CurrencyEnum.AOA]: { name: 'Angolan Kwanza', symbol: 'Kz' },
  [CurrencyEnum.AWG]: { name: 'Aruban Florin', symbol: 'ƒ' },
  [CurrencyEnum.AZN]: { name: 'Azerbaijani Manat', symbol: '₼' },
  [CurrencyEnum.BAM]: {
    name: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
  },
  [CurrencyEnum.BBD]: { name: 'Barbadian Dollar', symbol: 'Bds$' },
  [CurrencyEnum.BDT]: { name: 'Bangladeshi Taka', symbol: '৳' },
  [CurrencyEnum.BHD]: { name: 'Bahraini Dinar', symbol: 'د.ب' },
  [CurrencyEnum.BIF]: { name: 'Burundian Franc', symbol: 'FBu' },
  [CurrencyEnum.BMD]: { name: 'Bermudian Dollar', symbol: 'BD$' },
  [CurrencyEnum.BND]: { name: 'Brunei Dollar', symbol: 'B$' },
  [CurrencyEnum.BOB]: { name: 'Bolivian Boliviano', symbol: 'Bs' },
  [CurrencyEnum.BSD]: { name: 'Bahamian Dollar', symbol: 'B$' },
  [CurrencyEnum.BTN]: { name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  [CurrencyEnum.BWP]: { name: 'Botswanan Pula', symbol: 'P' },
  [CurrencyEnum.BYN]: { name: 'Belarusian Ruble', symbol: 'Br' },
  [CurrencyEnum.BZD]: { name: 'Belize Dollar', symbol: 'BZ$' },
  [CurrencyEnum.CDF]: { name: 'Congolese Franc', symbol: 'FC' },
  [CurrencyEnum.CRC]: { name: 'Costa Rican Colón', symbol: '₡' },
  [CurrencyEnum.CUP]: { name: 'Cuban Peso', symbol: '$MN' },
  [CurrencyEnum.CVE]: { name: 'Cape Verdean Escudo', symbol: 'CVE' },
  [CurrencyEnum.DJF]: { name: 'Djiboutian Franc', symbol: 'Fdj' },
  [CurrencyEnum.DOP]: { name: 'Dominican Peso', symbol: 'RD$' },
  [CurrencyEnum.DZD]: { name: 'Algerian Dinar', symbol: 'د.ج' },
  [CurrencyEnum.EGP]: { name: 'Egyptian Pound', symbol: 'E£' },
  [CurrencyEnum.ERN]: { name: 'Eritrean Nakfa', symbol: 'Nfk' },
  [CurrencyEnum.ETB]: { name: 'Ethiopian Birr', symbol: 'Br' },
  [CurrencyEnum.FJD]: { name: 'Fijian Dollar', symbol: 'FJ$' },
  [CurrencyEnum.GEL]: { name: 'Georgian Lari', symbol: '₾' },
  [CurrencyEnum.GHS]: { name: 'Ghanaian Cedi', symbol: '₵' },
  [CurrencyEnum.GMD]: { name: 'Gambian Dalasi', symbol: 'D' },
  [CurrencyEnum.GNF]: { name: 'Guinean Franc', symbol: 'FG' },
  [CurrencyEnum.GTQ]: { name: 'Guatemalan Quetzal', symbol: 'Q' },
  [CurrencyEnum.GYD]: { name: 'Guyanaese Dollar', symbol: 'G$' },
  [CurrencyEnum.HNL]: { name: 'Honduran Lempira', symbol: 'L' },
  [CurrencyEnum.HTG]: { name: 'Haitian Gourde', symbol: 'G' },
  [CurrencyEnum.IQD]: { name: 'Iraqi Dinar', symbol: 'ع.د' },
  [CurrencyEnum.IRR]: { name: 'Iranian Rial', symbol: '﷼' },
  [CurrencyEnum.ISK]: { name: 'Icelandic Króna', symbol: 'kr' },
  [CurrencyEnum.JMD]: { name: 'Jamaican Dollar', symbol: 'J$' },
  [CurrencyEnum.JOD]: { name: 'Jordanian Dinar', symbol: 'د.ا' },
  [CurrencyEnum.KES]: { name: 'Kenyan Shilling', symbol: 'KSh' },
  [CurrencyEnum.KGS]: { name: 'Kyrgystani Som', symbol: 'с' },
  [CurrencyEnum.KHR]: { name: 'Cambodian Riel', symbol: '៛' },
  [CurrencyEnum.KMF]: { name: 'Comorian Franc', symbol: 'CF' },
  [CurrencyEnum.KWD]: { name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  [CurrencyEnum.KYD]: { name: 'Cayman Islands Dollar', symbol: 'CI$' },
  [CurrencyEnum.KZT]: { name: 'Kazakhstani Tenge', symbol: '₸' },
  [CurrencyEnum.LAK]: { name: 'Laotian Kip', symbol: '₭' },
  [CurrencyEnum.LBP]: { name: 'Lebanese Pound', symbol: 'ل.ل' },
  [CurrencyEnum.LKR]: { name: 'Sri Lankan Rupee', symbol: 'Rs' },
  [CurrencyEnum.LRD]: { name: 'Liberian Dollar', symbol: 'L$' },
  [CurrencyEnum.LSL]: { name: 'Lesotho Loti', symbol: 'L' },
  [CurrencyEnum.LYD]: { name: 'Libyan Dinar', symbol: 'ل.د' },
  [CurrencyEnum.MAD]: { name: 'Moroccan Dirham', symbol: 'د.م.' },
  [CurrencyEnum.MDL]: { name: 'Moldovan Leu', symbol: 'L' },
  [CurrencyEnum.MGA]: { name: 'Malagasy Ariary', symbol: 'Ar' },
  [CurrencyEnum.MKD]: { name: 'Macedonian Denar', symbol: 'ден' },
  [CurrencyEnum.MMK]: { name: 'Myanmar Kyat', symbol: 'K' },
  [CurrencyEnum.MNT]: { name: 'Mongolian Tugrik', symbol: '₮' },
  [CurrencyEnum.MOP]: { name: 'Macanese Pataca', symbol: 'MOP$' },
  [CurrencyEnum.MUR]: { name: 'Mauritian Rupee', symbol: '₨' },
  [CurrencyEnum.MVR]: { name: 'Maldivian Rufiyaa', symbol: 'Rf' },
  [CurrencyEnum.MWK]: { name: 'Malawian Kwacha', symbol: 'MK' },
  [CurrencyEnum.MZN]: { name: 'Mozambican Metical', symbol: 'MT' },
  [CurrencyEnum.NAD]: { name: 'Namibian Dollar', symbol: 'N$' },
  [CurrencyEnum.NGN]: { name: 'Nigerian Naira', symbol: '₦' },
  [CurrencyEnum.NIO]: { name: 'Nicaraguan Córdoba', symbol: 'C$' },
  [CurrencyEnum.NPR]: { name: 'Nepalese Rupee', symbol: '₨' },
  [CurrencyEnum.OMR]: { name: 'Omani Rial', symbol: 'ر.ع.' },
  [CurrencyEnum.PAB]: { name: 'Panamanian Balboa', symbol: 'B/.' },
  [CurrencyEnum.PGK]: { name: 'Papua New Guinean Kina', symbol: 'K' },
  [CurrencyEnum.PKR]: { name: 'Pakistani Rupee', symbol: '₨' },
  [CurrencyEnum.PYG]: { name: 'Paraguayan Guarani', symbol: '₲' },
  [CurrencyEnum.QAR]: { name: 'Qatari Riyal', symbol: 'ر.ق' },
  [CurrencyEnum.RSD]: { name: 'Serbian Dinar', symbol: 'дин.' },
  [CurrencyEnum.RWF]: { name: 'Rwandan Franc', symbol: 'RF' },
  [CurrencyEnum.SBD]: { name: 'Solomon Islands Dollar', symbol: 'SI$' },
  [CurrencyEnum.SDG]: { name: 'Sudanese Pound', symbol: 'ج.س.' },
  [CurrencyEnum.SLE]: { name: 'Sierra Leonean Leone', symbol: 'Le' },
  [CurrencyEnum.SOS]: { name: 'Somali Shilling', symbol: 'Sh' },
  [CurrencyEnum.SRD]: { name: 'Surinamese Dollar', symbol: 'SRD' },
  [CurrencyEnum.SSP]: { name: 'South Sudanese Pound', symbol: 'SSP' },
  [CurrencyEnum.STN]: { name: 'São Tomé & Príncipe Dobra', symbol: 'Db' },
  [CurrencyEnum.SYP]: { name: 'Syrian Pound', symbol: 'ل.س' },
  [CurrencyEnum.SZL]: { name: 'Swazi Lilangeni', symbol: 'E' },
  [CurrencyEnum.TJS]: { name: 'Tajikistani Somoni', symbol: 'ЅМ' },
  [CurrencyEnum.TMT]: { name: 'Turkmenistani Manat', symbol: 'm' },
  [CurrencyEnum.TND]: { name: 'Tunisian Dinar', symbol: 'د.ت' },
  [CurrencyEnum.TOP]: { name: 'Tongan Paʻanga', symbol: 'T$' },
  [CurrencyEnum.TTD]: { name: 'Trinidad & Tobago Dollar', symbol: 'TT$' },
  [CurrencyEnum.TZS]: { name: 'Tanzanian Shilling', symbol: 'TSh' },
  [CurrencyEnum.UAH]: { name: 'Ukrainian Hryvnia', symbol: '₴' },
  [CurrencyEnum.UGX]: { name: 'Ugandan Shilling', symbol: 'USh' },
  [CurrencyEnum.UZS]: { name: 'Uzbekistani Som', symbol: 'soʻm' },
  [CurrencyEnum.VED]: { name: 'Venezuelan Bolívar Digital', symbol: 'Bs.D' },
  [CurrencyEnum.VUV]: { name: 'Vanuatu Vatu', symbol: 'VT' },
  [CurrencyEnum.WST]: { name: 'Samoan Tala', symbol: 'T' },
  [CurrencyEnum.XAF]: { name: 'Central African CFA Franc', symbol: 'FCFA' },
  [CurrencyEnum.XCD]: { name: 'East Caribbean Dollar', symbol: 'EC$' },
  [CurrencyEnum.XCG]: { name: 'Caribbean Guilder', symbol: 'Cg' },
  [CurrencyEnum.XOF]: { name: 'West African CFA Franc', symbol: 'CFA' },
  [CurrencyEnum.XPF]: { name: 'CFP Franc', symbol: '₣' },
  [CurrencyEnum.YER]: { name: 'Yemeni Rial', symbol: '﷼' },
  [CurrencyEnum.ZMW]: { name: 'Zambian Kwacha', symbol: 'ZK' },
  [CurrencyEnum.ZWG]: { name: 'Zimbabwe Gold', symbol: 'ZiG' },
};

/**
 * The single source of truth for currency display metadata.
 *
 * @description - Keyed by {@link CurrencyEnum}, so the compiler rejects both a missing
 *                and an unknown key. Adding a code to the enum therefore breaks the build
 *                until its name/symbol are supplied here. Only active ISO 4217 codes are
 *                listed; retired codes (EEK, LTL, LVL, HRK, VEF, ZMK, ZWL, ANG, SLL) were dropped
 *                in favour of their successors (EUR, VES, ZMW, ZWG, XCG, SLE).
 *                Fund and precious-metal codes (XDR, XAU, XAG, …) are out of scope.
 *                The `code` is derived from the key, so the two can never drift apart.
 */
export const CURRENCY_CATALOG: Record<CurrencyEnum, CurrencyMetadata> =
  Object.values(CurrencyEnum).reduce(
    (acc, code) => {
      const currencyCode = code as CurrencyEnum;
      acc[currencyCode] = {
        ...BASE_CURRENCY_DATA[currencyCode],
        code: currencyCode,
      };
      return acc;
    },
    {} as Record<CurrencyEnum, CurrencyMetadata>,
  );
