export enum ProductActionsEnum {
  CREATE = 'CREATE',
  RENEW = 'RENEW',
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  TRANSFER = 'TRANSFER',
  TRADE = 'TRADE',
  SUSPEND = 'SUSPEND',
  UNSUSPEND = 'UNSUSPEND',
  DELETE = 'DELETE',
}
