import { createCountry } from '../interfaces/country.interface';

export const COUNTRIES = {
  AF: createCountry('Afghanistan', 'AF'),
  AL: createCountry('Albania', 'AL'),
  DZ: createCountry('Algeria', 'DZ'),
  AS: createCountry('American Samoa', 'AS'),
  AD: createCountry('Andorra', 'AD'),
  AO: createCountry('Angola', 'AO'),
  AI: createCountry('Anguilla', 'AI'),
  AQ: createCountry('Antarctica', 'AQ'),
  AG: createCountry('Antigua and Barbuda', 'AG'),
  AR: createCountry('Argentina', 'AR'),
  AM: createCountry('Armenia', 'AM'),
  AW: createCountry('Aruba', 'AW'),
  AU: createCountry('Australia', 'AU'),
  AT: createCountry('Austria', 'AT'),
  AZ: createCountry('Azerbaijan', 'AZ'),
  BS: createCountry('Bahamas', 'BS'),
  BH: createCountry('Bahrain', 'BH'),
  BD: createCountry('Bangladesh', 'BD'),
  BB: createCountry('Barbados', 'BB'),
  BY: createCountry('Belarus', 'BY'),
  BE: createCountry('Belgium', 'BE'),
  BZ: createCountry('Belize', 'BZ'),
  BJ: createCountry('Benin', 'BJ'),
  BM: createCountry('Bermuda', 'BM'),
  BT: createCountry('Bhutan', 'BT'),
  BO: createCountry('Bolivia', 'BO'),
  BA: createCountry('Bosnia and Herzegovina', 'BA'),
  BW: createCountry('Botswana', 'BW'),
  BV: createCountry('Bouvet Island', 'BV'),
  BR: createCountry('Brazil', 'BR'),
  IO: createCountry('British Indian Ocean Territory', 'IO'),
  BN: createCountry('Brunei Darussalam', 'BN'),
  BG: createCountry('Bulgaria', 'BG'),
  BF: createCountry('Burkina Faso', 'BF'),
  BI: createCountry('Burundi', 'BI'),
  KH: createCountry('Cambodia', 'KH'),
  CM: createCountry('Cameroon', 'CM'),
  CA: createCountry('Canada', 'CA'),
  CV: createCountry('Cape Verde', 'CV'),
  KY: createCountry('Cayman Islands', 'KY'),
  CF: createCountry('Central African Republic', 'CF'),
  TD: createCountry('Chad', 'TD'),
  CL: createCountry('Chile', 'CL'),
  CN: createCountry('China', 'CN'),
  CX: createCountry('Christmas Island', 'CX'),
  CC: createCountry('Cocos (Keeling) Islands', 'CC'),
  CO: createCountry('Colombia', 'CO'),
  KM: createCountry('Comoros', 'KM'),
  CG: createCountry('Congo', 'CG'),
  CD: createCountry('Congo, the Democratic Republic of the', 'CD'),
  CK: createCountry('Cook Islands', 'CK'),
  CR: createCountry('Costa Rica', 'CR'),
  CI: createCountry('Côte d\'Ivoire', 'CI'),
  HR: createCountry('Croatia', 'HR'),
  CU: createCountry('Cuba', 'CU'),
  CY: createCountry('Cyprus', 'CY'),
  CZ: createCountry('Czech Republic', 'CZ'),
  DK: createCountry('Denmark', 'DK'),
  DJ: createCountry('Djibouti', 'DJ'),
  DM: createCountry('Dominica', 'DM'),
  DO: createCountry('Dominican Republic', 'DO'),
  EC: createCountry('Ecuador', 'EC'),
  EG: createCountry('Egypt', 'EG'),
  SV: createCountry('El Salvador', 'SV'),
  GQ: createCountry('Equatorial Guinea', 'GQ'),
  ER: createCountry('Eritrea', 'ER'),
  EE: createCountry('Estonia', 'EE'),
  ET: createCountry('Ethiopia', 'ET'),
  FK: createCountry('Falkland Islands (Malvinas)', 'FK'),
  FO: createCountry('Faroe Islands', 'FO'),
  FJ: createCountry('Fiji', 'FJ'),
  FI: createCountry('Finland', 'FI'),
  FR: createCountry('France', 'FR'),
  GF: createCountry('French Guiana', 'GF'),
  PF: createCountry('French Polynesia', 'PF'),
  TF: createCountry('French Southern Territories', 'TF'),
  GA: createCountry('Gabon', 'GA'),
  GM: createCountry('Gambia', 'GM'),
  GE: createCountry('Georgia', 'GE'),
  DE: createCountry('Germany', 'DE'),
  GH: createCountry('Ghana', 'GH'),
  GI: createCountry('Gibraltar', 'GI'),
  GR: createCountry('Greece', 'GR'),
  GL: createCountry('Greenland', 'GL'),
  GD: createCountry('Grenada', 'GD'),
  GP: createCountry('Guadeloupe', 'GP'),
  GU: createCountry('Guam', 'GU'),
  GT: createCountry('Guatemala', 'GT'),
  GG: createCountry('Guernsey', 'GG'),
  GN: createCountry('Guinea', 'GN'),
  GW: createCountry('Guinea-Bissau', 'GW'),
  GY: createCountry('Guyana', 'GY'),
  HT: createCountry('Haiti', 'HT'),
  HM: createCountry('Heard Island and McDonald Islands', 'HM'),
  VA: createCountry('Holy See (Vatican City State)', 'VA'),
  HN: createCountry('Honduras', 'HN'),
  HK: createCountry('Hong Kong', 'HK'),
  HU: createCountry('Hungary', 'HU'),
  IS: createCountry('Iceland', 'IS'),
  IN: createCountry('India', 'IN'),
  ID: createCountry('Indonesia', 'ID'),
  IR: createCountry('Iran, Islamic Republic of', 'IR'),
  IQ: createCountry('Iraq', 'IQ'),
  IE: createCountry('Ireland', 'IE'),
  IM: createCountry('Isle of Man', 'IM'),
  IL: createCountry('Israel', 'IL'),
  IT: createCountry('Italy', 'IT'),
  JM: createCountry('Jamaica', 'JM'),
  JP: createCountry('Japan', 'JP'),
  JE: createCountry('Jersey', 'JE'),
  JO: createCountry('Jordan', 'JO'),
  KZ: createCountry('Kazakhstan', 'KZ'),
  KE: createCountry('Kenya', 'KE'),
  KI: createCountry('Kiribati', 'KI'),
  KP: createCountry('Korea, Democratic People\'s Republic of', 'KP'),
  KR: createCountry('Korea, Republic of', 'KR'),
  KW: createCountry('Kuwait', 'KW'),
  KG: createCountry('Kyrgyzstan', 'KG'),
  LA: createCountry('Lao People\'s Democratic Republic', 'LA'),
  LV: createCountry('Latvia', 'LV'),
  LB: createCountry('Lebanon', 'LB'),
  LS: createCountry('Lesotho', 'LS'),
  LR: createCountry('Liberia', 'LR'),
  LY: createCountry('Libyan Arab Jamahiriya', 'LY'),
  LI: createCountry('Liechtenstein', 'LI'),
  LT: createCountry('Lithuania', 'LT'),
  LU: createCountry('Luxembourg', 'LU'),
  MO: createCountry('Macao', 'MO'),
  MK: createCountry('Macedonia, the former Yugoslav Republic of', 'MK'),
  MG: createCountry('Madagascar', 'MG'),
  MW: createCountry('Malawi', 'MW'),
  MY: createCountry('Malaysia', 'MY'),
  MV: createCountry('Maldives', 'MV'),
  ML: createCountry('Mali', 'ML'),
  MT: createCountry('Malta', 'MT'),
  MH: createCountry('Marshall Islands', 'MH'),
  MQ: createCountry('Martinique', 'MQ'),
  MR: createCountry('Mauritania', 'MR'),
  MU: createCountry('Mauritius', 'MU'),
  YT: createCountry('Mayotte', 'YT'),
  MX: createCountry('Mexico', 'MX'),
  FM: createCountry('Micronesia, Federated States of', 'FM'),
  MD: createCountry('Moldova, Republic of', 'MD'),
  MC: createCountry('Monaco', 'MC'),
  MN: createCountry('Mongolia', 'MN'),
  ME: createCountry('Montenegro', 'ME'),
  MS: createCountry('Montserrat', 'MS'),
  MA: createCountry('Morocco', 'MA'),
  MZ: createCountry('Mozambique', 'MZ'),
  MM: createCountry('Myanmar', 'MM'),
  NA: createCountry('Namibia', 'NA'),
  NR: createCountry('Nauru', 'NR'),
  NP: createCountry('Nepal', 'NP'),
  NL: createCountry('Netherlands', 'NL'),
  AN: createCountry('Netherlands Antilles', 'AN'),
  NC: createCountry('New Caledonia', 'NC'),
  NZ: createCountry('New Zealand', 'NZ'),
  NI: createCountry('Nicaragua', 'NI'),
  NE: createCountry('Niger', 'NE'),
  NG: createCountry('Nigeria', 'NG'),
  NU: createCountry('Niue', 'NU'),
  NF: createCountry('Norfolk Island', 'NF'),
  MP: createCountry('Northern Mariana Islands', 'MP'),
  NO: createCountry('Norway', 'NO'),
  OM: createCountry('Oman', 'OM'),
  PK: createCountry('Pakistan', 'PK'),
  PW: createCountry('Palau', 'PW'),
  PS: createCountry('Palestinian Territory, Occupied', 'PS'),
  PA: createCountry('Panama', 'PA'),
  PG: createCountry('Papua New Guinea', 'PG'),
  PY: createCountry('Paraguay', 'PY'),
  PE: createCountry('Peru', 'PE'),
  PH: createCountry('Philippines', 'PH'),
  PN: createCountry('Pitcairn', 'PN'),
  PL: createCountry('Poland', 'PL'),
  PT: createCountry('Portugal', 'PT'),
  PR: createCountry('Puerto Rico', 'PR'),
  QA: createCountry('Qatar', 'QA'),
  RE: createCountry('Réunion', 'RE'),
  RO: createCountry('Romania', 'RO'),
  RU: createCountry('Russian Federation', 'RU'),
  RW: createCountry('Rwanda', 'RW'),
  SH: createCountry('Saint Helena', 'SH'),
  KN: createCountry('Saint Kitts and Nevis', 'KN'),
  LC: createCountry('Saint Lucia', 'LC'),
  PM: createCountry('Saint Pierre and Miquelon', 'PM'),
  VC: createCountry('Saint Vincent and the Grenadines', 'VC'),
  WS: createCountry('Samoa', 'WS'),
  SM: createCountry('San Marino', 'SM'),
  ST: createCountry('Sao Tome and Principe', 'ST'),
  SA: createCountry('Saudi Arabia', 'SA'),
  SN: createCountry('Senegal', 'SN'),
  RS: createCountry('Serbia', 'RS'),
  SC: createCountry('Seychelles', 'SC'),
  SL: createCountry('Sierra Leone', 'SL'),
  SG: createCountry('Singapore', 'SG'),
  SK: createCountry('Slovakia', 'SK'),
  SI: createCountry('Slovenia', 'SI'),
  SB: createCountry('Solomon Islands', 'SB'),
  SO: createCountry('Somalia', 'SO'),
  ZA: createCountry('South Africa', 'ZA'),
  GS: createCountry('South Georgia and the South Sandwich Islands', 'GS'),
  ES: createCountry('Spain', 'ES'),
  LK: createCountry('Sri Lanka', 'LK'),
  SD: createCountry('Sudan', 'SD'),
  SR: createCountry('Suriname', 'SR'),
  SJ: createCountry('Svalbard and Jan Mayen', 'SJ'),
  SZ: createCountry('Swaziland', 'SZ'),
  SE: createCountry('Sweden', 'SE'),
  CH: createCountry('Switzerland', 'CH'),
  SY: createCountry('Syrian Arab Republic', 'SY'),
  TW: createCountry('Taiwan, Province of China', 'TW'),
  TJ: createCountry('Tajikistan', 'TJ'),
  TZ: createCountry('Tanzania, United Republic of', 'TZ'),
  TH: createCountry('Thailand', 'TH'),
  TL: createCountry('Timor-Leste', 'TL'),
  TG: createCountry('Togo', 'TG'),
  TK: createCountry('Tokelau', 'TK'),
  TO: createCountry('Tonga', 'TO'),
  TT: createCountry('Trinidad and Tobago', 'TT'),
  TN: createCountry('Tunisia', 'TN'),
  TR: createCountry('Turkey', 'TR'),
  TM: createCountry('Turkmenistan', 'TM'),
  TC: createCountry('Turks and Caicos Islands', 'TC'),
  TV: createCountry('Tuvalu', 'TV'),
  UG: createCountry('Uganda', 'UG'),
  UA: createCountry('Ukraine', 'UA'),
  AE: createCountry('United Arab Emirates', 'AE'),
  GB: createCountry('United Kingdom', 'GB'),
  US: createCountry('United States', 'US'),
  UM: createCountry('United States Minor Outlying Islands', 'UM'),
  UY: createCountry('Uruguay', 'UY'),
  UZ: createCountry('Uzbekistan', 'UZ'),
  VU: createCountry('Vanuatu', 'VU'),
  VE: createCountry('Venezuela, Bolivarian Republic of', 'VE'),
  VN: createCountry('Viet Nam', 'VN'),
  VG: createCountry('Virgin Islands, British', 'VG'),
  VI: createCountry('Virgin Islands, U.S.', 'VI'),
  WF: createCountry('Wallis and Futuna', 'WF'),
  EH: createCountry('Western Sahara', 'EH'),
  YE: createCountry('Yemen', 'YE'),
  ZM: createCountry('Zambia', 'ZM'),
  ZW: createCountry('Zimbabwe', 'ZW'),
  // Alias for United Kingdom
  UK: createCountry('United Kingdom', 'UK')
} as const;

/**
 * Comprehensive list of all countries that are geographically in Europe
 * Includes EU members, EEA, microstates, and other European countries
 */
export const GEOGRAPHIC_EUROPEAN_COUNTRIES = new Set([
  // EU Member States
  'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR',
  'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
  'SI', 'ES', 'SE',
  
  // Non-EU European countries
  'AL', 'AD', 'BA', 'BY', 'FO', 'GI', 'GG', 'IS', 'IM', 'JE', 'XK', 'LI',
  'MD', 'MC', 'ME', 'MK', 'NO', 'RU', 'SM', 'RS', 'CH', 'UA', 'VA', 'UK', 'GB'
]);

/**
 * List of EU/EEA member countries for regulatory/trade purposes
 */
export const EU_EEA_COUNTRIES = new Set([
  // EU Members
  'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR',
  'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
  'SI', 'ES', 'SE',
  // EEA (EU + Norway, Iceland, Liechtenstein)
  'IS', 'LI', 'NO',
  // Special cases
  'CH'  // Switzerland has bilateral agreements
]);

export const EUROPEAN_COUNTRY_CODES = Array.from(EU_EEA_COUNTRIES).sort();

